"use client";
import Link from"next/link";import{useCallback,useEffect,useMemo,useState}from"react";import AppNav from"@/app/components/AppNav";import AuthGuard from"@/app/components/AuthGuard";import{supabase}from"@/lib/supabaseClient";import{getWorkspaceScope}from"@/lib/workspace";import type{UserRole}from"@/lib/types";
type Alert={id:string;type:string;severity:"info"|"warning"|"critical";title:string;message:string;action_url:string|null;last_detected_at:string};type State={alert_id:string;read_at:string|null;dismissed_at:string|null};type Prefs={expiry_warning_days:number;projected_stockout_days:number;customer_balance_overdue_days:number;supplier_balance_overdue_days:number;fast_selling_multiplier:number};
const defaults:Prefs={expiry_warning_days:30,projected_stockout_days:7,customer_balance_overdue_days:7,supplier_balance_overdue_days:7,fast_selling_multiplier:1.5};
export default function AlertsPage(){const[alerts,setAlerts]=useState<Alert[]>([]);const[states,setStates]=useState<State[]>([]);const[prefs,setPrefs]=useState<Prefs>(defaults);const[role,setRole]=useState<UserRole>("staff");const[severity,setSeverity]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
const load=useCallback(async()=>{const scope=await getWorkspaceScope();setRole(scope.profile?.role??"staff");const[a,s,p]=await Promise.all([supabase.from("alerts").select("id,type,severity,title,message,action_url,last_detected_at").eq("is_active",true).order("severity").order("last_detected_at",{ascending:false}),supabase.from("alert_user_states").select("alert_id,read_at,dismissed_at"),supabase.from("alert_preferences").select("*").maybeSingle()]);setAlerts((a.data??[])as Alert[]);setStates((s.data??[])as State[]);if(p.data)setPrefs(p.data as Prefs);setMessage(a.error?.message??s.error?.message??p.error?.message??"");setLoading(false);},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);
const stateMap=useMemo(()=>new Map(states.map(s=>[s.alert_id,s])),[states]);const visible=alerts.filter(a=>(!severity||a.severity===severity)&&!stateMap.get(a.id)?.dismissed_at);const unread=visible.filter(a=>!stateMap.get(a.id)?.read_at).length;
const refresh=async()=>{setLoading(true);const{data,error}=await supabase.rpc("refresh_workspace_alerts");setMessage(error?.message??`${data} active alert${data===1?"":"s"} generated.`);await load();};
const setState=async(id:string,kind:"read"|"dismiss")=>{const scope=await getWorkspaceScope();if(!scope.userId)return;const payload={alert_id:id,user_id:scope.userId,...(kind==="read"?{read_at:new Date().toISOString()}:{dismissed_at:new Date().toISOString(),read_at:new Date().toISOString()})};const{error}=await supabase.from("alert_user_states").upsert(payload,{onConflict:"alert_id,user_id"});setMessage(error?.message??"");if(!error)await load();};
const savePrefs=async()=>{const scope=await getWorkspaceScope();if(!scope.userId||!scope.workspaceId)return;const{error}=await supabase.from("alert_preferences").upsert({...prefs,workspace_id:scope.workspaceId,updated_by:scope.userId,updated_at:new Date().toISOString()});setMessage(error?.message??"Alert preferences saved.");if(!error)await refresh();};const manager=role==="owner"||role==="admin";const input="rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3";
return <AuthGuard><main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100 sm:px-12"><div className="mx-auto max-w-7xl space-y-8"><AppNav/><header className="flex flex-col gap-5 rounded-[2rem] border border-white/10 bg-slate-900/80 p-8 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm uppercase tracking-[.3em] text-emerald-300">Action center</p><h1 className="mt-3 text-3xl font-semibold">Alerts and recommendations</h1><p className="mt-2 text-slate-400">{unread} unread · Generated only from current business data</p></div><button onClick={refresh}className="rounded-full bg-emerald-500 px-6 py-3 font-semibold text-slate-950">Refresh alerts</button></header>{message&&<p className="rounded-2xl bg-amber-400/10 p-4 text-amber-200">{message}</p>}
<section className="rounded-[2rem] border border-white/10 bg-slate-900/80 p-7"><select value={severity}onChange={e=>setSeverity(e.target.value)}className={input}><option value="">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Information</option></select><div className="mt-6 space-y-3">{loading?<p className="text-slate-400">Evaluating business data…</p>:visible.length===0?<p className="text-slate-400">No active alerts. Your workspace looks healthy.</p>:visible.map(a=>{const read=Boolean(stateMap.get(a.id)?.read_at);return <article key={a.id}className={`rounded-2xl border p-5 ${a.severity==="critical"?"border-rose-500/30 bg-rose-500/10":a.severity==="warning"?"border-amber-400/25 bg-amber-400/10":"border-cyan-400/20 bg-cyan-400/10"} ${read?"opacity-70":""}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-slate-400">{a.type.replaceAll("_"," ")}</p><h2 className="mt-1 font-semibold">{a.title}</h2><p className="mt-2 text-sm text-slate-300">{a.message}</p></div><div className="flex shrink-0 gap-2">{a.action_url&&<Link href={a.action_url}onClick={()=>setState(a.id,"read")}className="rounded-full bg-slate-950/60 px-4 py-2 text-sm text-emerald-300">Take action</Link>}{!read&&<button onClick={()=>setState(a.id,"read")}className="rounded-full bg-slate-800 px-4 py-2 text-sm">Mark read</button>}<button onClick={()=>setState(a.id,"dismiss")}className="rounded-full px-3 py-2 text-sm text-slate-400">Dismiss</button></div></div></article>})}</div></section>
{manager&&<section className="rounded-[2rem] border border-white/10 bg-slate-900/80 p-7"><h2 className="text-xl font-semibold">Alert preferences</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><NumberPref label="Expiry warning days"value={prefs.expiry_warning_days}onChange={v=>setPrefs({...prefs,expiry_warning_days:v})}/><NumberPref label="Projected stockout days"value={prefs.projected_stockout_days}onChange={v=>setPrefs({...prefs,projected_stockout_days:v})}/><NumberPref label="Customer overdue days"value={prefs.customer_balance_overdue_days}onChange={v=>setPrefs({...prefs,customer_balance_overdue_days:v})}/><NumberPref label="Supplier overdue days"value={prefs.supplier_balance_overdue_days}onChange={v=>setPrefs({...prefs,supplier_balance_overdue_days:v})}/><NumberPref label="Fast-selling multiplier"value={prefs.fast_selling_multiplier}step=".1"onChange={v=>setPrefs({...prefs,fast_selling_multiplier:v})}/></div><button onClick={savePrefs}className="mt-6 rounded-full bg-emerald-500 px-6 py-3 font-semibold text-slate-950">Save preferences</button></section>}</div></main></AuthGuard>;}
function NumberPref({label,value,onChange,step="1"}:{label:string;value:number;onChange:(v:number)=>void;step?:string}){return <label className="text-sm text-slate-300">{label}<input type="number"min="1"step={step}value={value}onChange={e=>onChange(Number(e.target.value))}className="mt-2 w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3"/></label>;}
