"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import AppNav from "@/app/components/AppNav";
import AuthGuard from "@/app/components/AuthGuard";
import { supabase } from "@/lib/supabaseClient";
import type { Customer, Product } from "@/lib/types";

type Line={product_id:string;quantity:number};
export default function NewSalePage(){
  const router=useRouter();const [products,setProducts]=useState<Product[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);
  const [lines,setLines]=useState<Line[]>([{product_id:"",quantity:1}]);const [customer,setCustomer]=useState("");const [discount,setDiscount]=useState(0);const [tax,setTax]=useState(0);const [method,setMethod]=useState("cash");const [paid,setPaid]=useState(0);const [notes,setNotes]=useState("");const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{void Promise.all([supabase.from("products").select("id,name,sku,quantity,cost_price,selling_price,reorder_threshold,category_id,description,overstock_threshold,supplier,image_url,unit,expiry_date,barcode").gt("quantity",0).order("name"),supabase.from("customers").select("id,name,email,phone,address,notes").order("name")]).then(([p,c])=>{setProducts((p.data??[]) as Product[]);setCustomers((c.data??[]) as Customer[]);setMessage(p.error?.message??c.error?.message??"");});},[]);
  const subtotal=useMemo(()=>lines.reduce((sum,line)=>sum+(products.find(p=>p.id===line.product_id)?.selling_price??0)*Number(line.quantity||0),0),[lines,products]);const total=Math.max(0,subtotal-discount+tax);
  const update=(index:number,patch:Partial<Line>)=>setLines(current=>current.map((line,i)=>i===index?{...line,...patch}:line));
  const save=async()=>{setMessage("");if(lines.some(l=>!l.product_id||l.quantity<=0))return setMessage("Choose a product and positive quantity for every line.");if(discount>subtotal)return setMessage("Discount cannot exceed subtotal.");setSaving(true);const {data,error}=await supabase.rpc("create_sale",{p_customer_id:customer||null,p_items:lines,p_discount:discount,p_tax:tax,p_payment_method:method,p_amount_paid:paid,p_notes:notes||null});setSaving(false);if(error)return setMessage(error.message);const sale=Array.isArray(data)?data[0]:data;router.push(`/sales/${sale.id}`);};
  const input="rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3";
  return <AuthGuard><main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100 sm:px-12"><div className="mx-auto max-w-5xl space-y-8"><AppNav/><header className="rounded-[2rem] border border-white/10 bg-slate-900/80 p-8"><p className="text-sm uppercase tracking-[.3em] text-emerald-300">Checkout</p><h1 className="mt-3 text-3xl font-semibold">Record a sale</h1><p className="mt-2 text-slate-400">Stock is validated and reduced only when the complete transaction succeeds.</p></header>
    {message&&<p className="rounded-2xl bg-amber-400/10 p-4 text-amber-200">{message}</p>}<section className="rounded-[2rem] border border-white/10 bg-slate-900/80 p-7"><div className="space-y-4">{lines.map((line,index)=><div key={index} className="grid gap-3 rounded-2xl bg-slate-950/70 p-4 sm:grid-cols-[1fr_140px_auto]"><select value={line.product_id} onChange={e=>update(index,{product_id:e.target.value})} className={input}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.quantity} available · {Number(p.selling_price).toLocaleString()}</option>)}</select><input type="number" min="1" value={line.quantity} onChange={e=>update(index,{quantity:Number(e.target.value)})} className={input}/><button disabled={lines.length===1} onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))} className="rounded-full px-4 text-rose-300 disabled:opacity-30">Remove</button></div>)}</div><button onClick={()=>setLines(current=>[...current,{product_id:"",quantity:1}])} className="mt-4 rounded-full bg-slate-800 px-5 py-3 text-emerald-300">+ Add product</button>
      <div className="mt-8 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Customer<select value={customer} onChange={e=>setCustomer(e.target.value)} className={`${input} mt-2 w-full`}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm text-slate-300">Payment method<select value={method} onChange={e=>setMethod(e.target.value)} className={`${input} mt-2 w-full`}><option value="cash">Cash</option><option value="card">Card</option><option value="transfer">Bank transfer</option><option value="mobile">Mobile payment</option><option value="credit">Credit</option></select></label><label className="text-sm text-slate-300">Discount<input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))} className={`${input} mt-2 w-full`}/></label><label className="text-sm text-slate-300">Tax<input type="number" min="0" value={tax} onChange={e=>setTax(Number(e.target.value))} className={`${input} mt-2 w-full`}/></label><label className="text-sm text-slate-300">Amount paid<input type="number" min="0" max={total} value={paid} onChange={e=>setPaid(Number(e.target.value))} className={`${input} mt-2 w-full`}/></label><label className="text-sm text-slate-300">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className={`${input} mt-2 w-full`}/></label></div>
      <div className="mt-8 flex flex-col gap-5 rounded-3xl bg-emerald-500/10 p-6 sm:flex-row sm:items-end sm:justify-between"><div className="space-y-1 text-sm text-slate-300"><p>Subtotal: {subtotal.toLocaleString()}</p><p>Discount: {discount.toLocaleString()}</p><p>Tax: {tax.toLocaleString()}</p><p className="pt-2 text-2xl font-semibold text-white">Total: {total.toLocaleString()}</p></div><button disabled={saving} onClick={save} className="rounded-full bg-emerald-500 px-7 py-4 font-semibold text-slate-950 disabled:opacity-50">{saving?"Processing…":"Complete sale"}</button></div>
    </section></div></main></AuthGuard>;
}
